-- MySQL Script generated by MySQL Workbench
-- Thu May  5 16:21:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema storex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema storex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `storex` DEFAULT CHARACTER SET utf8;
USE `storex`;

-- -----------------------------------------------------
-- Table `storex`.`usertype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storex`.`usertype`
(
    `ID`   INT         NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(45) NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storex`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storex`.`user`
(
    `ID`          INT         NOT NULL AUTO_INCREMENT,
    `FirstName`   VARCHAR(45) NOT NULL,
    `LastName`    VARCHAR(45) NOT NULL,
    `PhoneNumber` VARCHAR(12) NULL,
    `Email`       VARCHAR(45) NOT NULL,
    `usertype_ID` INT         NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
    UNIQUE INDEX `PhoneNumber_UNIQUE` (`PhoneNumber` ASC) VISIBLE,
    UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
    INDEX `fk_user_usertype_idx` (`usertype_ID` ASC) VISIBLE,
    CONSTRAINT `fk_user_usertype`
        FOREIGN KEY (`usertype_ID`)
            REFERENCES `storex`.`usertype` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storex`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storex`.`category`
(
    `ID`   INT         NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storex`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storex`.`articles`
(
    `ID`          INT          NOT NULL AUTO_INCREMENT,
    `Name`        VARCHAR(45)  NOT NULL,
    `Price`       DECIMAL(4)   NOT NULL,
    `Description` VARCHAR(500) NULL,
    `Image`       VARCHAR(45)  NOT NULL,
    `category_ID` INT          NOT NULL,
    `user_ID`     INT          NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
    INDEX `fk_articles_category1_idx` (`category_ID` ASC) VISIBLE,
    INDEX `fk_articles_user1_idx` (`user_ID` ASC) VISIBLE,
    CONSTRAINT `fk_articles_category1`
        FOREIGN KEY (`category_ID`)
            REFERENCES `storex`.`category` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_articles_user1`
        FOREIGN KEY (`user_ID`)
            REFERENCES `storex`.`user` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
