DROP DATABASE if exists storex;

-- MySQL Script generated by MySQL Workbench
-- Fri May  6 13:45:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema storex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema storex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `storex` DEFAULT CHARACTER SET utf8;
USE `storex`;

-- -----------------------------------------------------
-- Table `storex`.`userstypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storex`.`userstypes`
(
    `ID`   INT         NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(50) NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storex`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storex`.`users`
(
    `ID`          INT         NOT NULL AUTO_INCREMENT,
    `FirstName`   VARCHAR(50) NOT NULL,
    `LastName`    VARCHAR(50) NOT NULL,
    `PhoneNumber` VARCHAR(30) NULL,
    `Email`       VARCHAR(100) NOT NULL,
    `Password`    VARCHAR(1000) NOT NULL,
    `usertype_ID` INT         NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
    UNIQUE INDEX `PhoneNumber_UNIQUE` (`PhoneNumber` ASC) VISIBLE,
    UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
    INDEX `fk_user_usertype_idx` (`usertype_ID` ASC) VISIBLE,
    CONSTRAINT `fk_user_usertype`
        FOREIGN KEY (`usertype_ID`)
            REFERENCES `storex`.`userstypes` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storex`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storex`.`categories`
(
    `ID`   INT         NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `storex`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storex`.`articles`
(
    `ID`          INT          NOT NULL AUTO_INCREMENT,
    `Name`        VARCHAR(100)  NOT NULL,
    `Price`       DECIMAL(50)   NOT NULL,
    `Description` VARCHAR(10000) NULL,
    `Image`       VARCHAR(500)  NOT NULL,
    `category_ID` INT          NOT NULL,
    `user_ID`     INT          NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
    INDEX `fk_articles_category1_idx` (`category_ID` ASC) VISIBLE,
    INDEX `fk_articles_user1_idx` (`user_ID` ASC) VISIBLE,
    CONSTRAINT `fk_articles_category1`
        FOREIGN KEY (`category_ID`)
            REFERENCES `storex`.`categories` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_articles_user1`
        FOREIGN KEY (`user_ID`)
            REFERENCES `storex`.`users` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

INSERT INTO storex.categories (Name)
VALUES ('Femmes'),
       ('Hommes'),
       ('Enfants'),
       ('Accessoires');

INSERT INTO storex.userstypes (Name)
VALUES ('CEO'),
       ('CTO'),
       ('Vendor');


/* Création de l'utilisateur
CREATE USER IF NOT EXISTS 'StorexAutoAdmin'@'%' IDENTIFIED BY 'storex';
GRANT ALL PRIVILEGES ON *.* TO 'StorexAutoAdmin'@'%';
*/